export const products = [
  {
    id: 1,
    title: "Rose Bloom Hairband",
    category: "Hairbands",
    image: "https://res.cloudinary.com/dtcy9bbux/image/upload/v1784754115/poshsaaz/rose_bloom_hairband.jpg",
    description: "Handcrafted pipe cleaner floral hairband with vibrant pink rosettes and pearl accents.",
    details: "Each hairband is meticulously shaped from fuzzy chenille stem wire with delicate pearl embellishments. Perfect for weddings, events, or everyday elegance.",
    price: "Starting ₹249",
  },
  {
    id: 2,
    title: "Tulip Garden Bouquet",
    category: "Bouquets",
    image: "https://res.cloudinary.com/dtcy9bbux/image/upload/v1784754140/poshsaaz/tulip_garden_bouquet.jpg",
    description: "Stunning everlasting tulip bouquet crafted from handmade pipe cleaner blooms.",
    details: "Our signature everlasting bouquets combine traditional Kashmir craftsmanship with contemporary floral art. Wrapped in kraft paper with satin ribbon.",
    price: "Starting ₹399",
  },
  {
    id: 3,
    title: "Floral Clips Collection",
    category: "Clips & Combs",
    image: "https://res.cloudinary.com/dtcy9bbux/image/upload/v1784754165/poshsaaz/floral_clips_collection.jpg",
    description: "Fine floral clips with miniature pipe cleaner flowers and pearl centers.",
    details: "Precision-crafted miniature chenille floral clips with gold-tone hardware. Ideal for bridal wear and everyday styling.",
    price: "Starting ₹149",
  },
  {
    id: 4,
    title: "Pearl Blossom Comb",
    category: "Clips & Combs",
    image: "https://res.cloudinary.com/dtcy9bbux/image/upload/v1784754182/poshsaaz/pearl_blossom_comb.jpg",
    description: "Decorative hair comb with cascading handmade blossoms and pearls.",
    details: "Golden hair comb featuring handmade white and pink chenille wire flowers, golden leaves, and pearl accents.",
    price: "Starting ₹199",
  },
  {
    id: 5,
    title: "Floral Curtain Tieback",
    category: "Home Decor",
    image: "https://res.cloudinary.com/dtcy9bbux/image/upload/v1784756852/poshsaaz/curtain_tieback.jpg",
    description: "Handmade chenille floral curtain holdback with pink and purple blooms, pearl drops, and gold rope.",
    details: "Magnetic curtain tieback featuring handcrafted pipe cleaner flowers in pink and lavender with gold leaf accents and dangling pearl embellishments. Adds an elegant handmade touch to any curtain.",
    price: "Starting ₹299",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Amira Khan",
    role: "Bride",
    rating: 5,
    text: "The most beautiful hairband I've ever seen. The craftsmanship is impeccable and it made my wedding day extra special.",
  },
  {
    id: 2,
    name: "Fatima Ahmed",
    role: "Event Planner",
    rating: 5,
    text: "Poshsaaz creates magic with every piece. My clients are always amazed by the quality and attention to detail.",
  },
  {
    id: 3,
    name: "Zara Malik",
    role: "Fashion Designer",
    rating: 5,
    text: "The artistry and tradition in every creation is remarkable. I recommend Poshsaaz to all my clients.",
  },
  {
    id: 4,
    name: "Noor Hassan",
    role: "Customer",
    rating: 5,
    text: "Exceeded all my expectations. The bouquet arrived perfectly packaged and looked even better than the photos.",
  },
  {
    id: 5,
    name: "Leila Syed",
    role: "Bride",
    rating: 5,
    text: "Every detail was perfect. The team was so helpful and the final product was absolutely stunning.",
  },
];
